# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hod', [dirname(__file__)])
        except ImportError:
            import _hod
            return _hod
        if fp is not None:
            try:
                _mod = imp.load_module('_hod', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _hod = swig_import_helper()
    del swig_import_helper
else:
    import _hod
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_dArray(*args):
  return _hod.new_dArray(*args)
new_dArray = _hod.new_dArray

def delete_dArray(*args):
  return _hod.delete_dArray(*args)
delete_dArray = _hod.delete_dArray

def dArray_getitem(*args):
  return _hod.dArray_getitem(*args)
dArray_getitem = _hod.dArray_getitem

def dArray_setitem(*args):
  return _hod.dArray_setitem(*args)
dArray_setitem = _hod.dArray_setitem
class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _hod.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _hod.doubleArray___getitem__(self, *args)
    def __setitem__(self, *args): return _hod.doubleArray___setitem__(self, *args)
    def cast(self): return _hod.doubleArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _hod.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_hod.doubleArray_frompointer)
doubleArray_swigregister = _hod.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(*args):
  return _hod.doubleArray_frompointer(*args)
doubleArray_frompointer = _hod.doubleArray_frompointer

class cosmo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cosmo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cosmo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Om0"] = _hod.cosmo_Om0_set
    __swig_getmethods__["Om0"] = _hod.cosmo_Om0_get
    if _newclass:Om0 = _swig_property(_hod.cosmo_Om0_get, _hod.cosmo_Om0_set)
    __swig_setmethods__["Omk"] = _hod.cosmo_Omk_set
    __swig_getmethods__["Omk"] = _hod.cosmo_Omk_get
    if _newclass:Omk = _swig_property(_hod.cosmo_Omk_get, _hod.cosmo_Omk_set)
    __swig_setmethods__["w0"] = _hod.cosmo_w0_set
    __swig_getmethods__["w0"] = _hod.cosmo_w0_get
    if _newclass:w0 = _swig_property(_hod.cosmo_w0_get, _hod.cosmo_w0_set)
    __swig_setmethods__["wa"] = _hod.cosmo_wa_set
    __swig_getmethods__["wa"] = _hod.cosmo_wa_get
    if _newclass:wa = _swig_property(_hod.cosmo_wa_get, _hod.cosmo_wa_set)
    __swig_setmethods__["Omb"] = _hod.cosmo_Omb_set
    __swig_getmethods__["Omb"] = _hod.cosmo_Omb_get
    if _newclass:Omb = _swig_property(_hod.cosmo_Omb_get, _hod.cosmo_Omb_set)
    __swig_setmethods__["hval"] = _hod.cosmo_hval_set
    __swig_getmethods__["hval"] = _hod.cosmo_hval_get
    if _newclass:hval = _swig_property(_hod.cosmo_hval_get, _hod.cosmo_hval_set)
    __swig_setmethods__["th"] = _hod.cosmo_th_set
    __swig_getmethods__["th"] = _hod.cosmo_th_get
    if _newclass:th = _swig_property(_hod.cosmo_th_get, _hod.cosmo_th_set)
    __swig_setmethods__["s8"] = _hod.cosmo_s8_set
    __swig_getmethods__["s8"] = _hod.cosmo_s8_get
    if _newclass:s8 = _swig_property(_hod.cosmo_s8_get, _hod.cosmo_s8_set)
    __swig_setmethods__["nspec"] = _hod.cosmo_nspec_set
    __swig_getmethods__["nspec"] = _hod.cosmo_nspec_get
    if _newclass:nspec = _swig_property(_hod.cosmo_nspec_get, _hod.cosmo_nspec_set)
    __swig_setmethods__["ximax"] = _hod.cosmo_ximax_set
    __swig_getmethods__["ximax"] = _hod.cosmo_ximax_get
    if _newclass:ximax = _swig_property(_hod.cosmo_ximax_get, _hod.cosmo_ximax_set)
    __swig_setmethods__["cfac"] = _hod.cosmo_cfac_set
    __swig_getmethods__["cfac"] = _hod.cosmo_cfac_get
    if _newclass:cfac = _swig_property(_hod.cosmo_cfac_get, _hod.cosmo_cfac_set)
    def __init__(self): 
        this = _hod.new_cosmo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_cosmo
    __del__ = lambda self : None;
cosmo_swigregister = _hod.cosmo_swigregister
cosmo_swigregister(cosmo)

class gf_par(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, gf_par, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, gf_par, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Omega0"] = _hod.gf_par_Omega0_set
    __swig_getmethods__["Omega0"] = _hod.gf_par_Omega0_get
    if _newclass:Omega0 = _swig_property(_hod.gf_par_Omega0_get, _hod.gf_par_Omega0_set)
    __swig_setmethods__["OmegaL"] = _hod.gf_par_OmegaL_set
    __swig_getmethods__["OmegaL"] = _hod.gf_par_OmegaL_get
    if _newclass:OmegaL = _swig_property(_hod.gf_par_OmegaL_get, _hod.gf_par_OmegaL_set)
    __swig_setmethods__["w0"] = _hod.gf_par_w0_set
    __swig_getmethods__["w0"] = _hod.gf_par_w0_get
    if _newclass:w0 = _swig_property(_hod.gf_par_w0_get, _hod.gf_par_w0_set)
    __swig_setmethods__["wa"] = _hod.gf_par_wa_set
    __swig_getmethods__["wa"] = _hod.gf_par_wa_get
    if _newclass:wa = _swig_property(_hod.gf_par_wa_get, _hod.gf_par_wa_set)
    def __init__(self): 
        this = _hod.new_gf_par()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_gf_par
    __del__ = lambda self : None;
gf_par_swigregister = _hod.gf_par_swigregister
gf_par_swigregister(gf_par)

class qk_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, qk_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, qk_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.qk_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.qk_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.qk_params_cptr_get, _hod.qk_params_cptr_set)
    __swig_setmethods__["k"] = _hod.qk_params_k_set
    __swig_getmethods__["k"] = _hod.qk_params_k_get
    if _newclass:k = _swig_property(_hod.qk_params_k_get, _hod.qk_params_k_set)
    __swig_setmethods__["z"] = _hod.qk_params_z_set
    __swig_getmethods__["z"] = _hod.qk_params_z_get
    if _newclass:z = _swig_property(_hod.qk_params_z_get, _hod.qk_params_z_set)
    __swig_setmethods__["xmax"] = _hod.qk_params_xmax_set
    __swig_getmethods__["xmax"] = _hod.qk_params_xmax_get
    if _newclass:xmax = _swig_property(_hod.qk_params_xmax_get, _hod.qk_params_xmax_set)
    __swig_setmethods__["opt"] = _hod.qk_params_opt_set
    __swig_getmethods__["opt"] = _hod.qk_params_opt_get
    if _newclass:opt = _swig_property(_hod.qk_params_opt_get, _hod.qk_params_opt_set)
    def __init__(self): 
        this = _hod.new_qk_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_qk_params
    __del__ = lambda self : None;
qk_params_swigregister = _hod.qk_params_swigregister
qk_params_swigregister(qk_params)

class projwpk_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, projwpk_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, projwpk_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.projwpk_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.projwpk_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.projwpk_params_cptr_get, _hod.projwpk_params_cptr_set)
    __swig_setmethods__["R"] = _hod.projwpk_params_R_set
    __swig_getmethods__["R"] = _hod.projwpk_params_R_get
    if _newclass:R = _swig_property(_hod.projwpk_params_R_get, _hod.projwpk_params_R_set)
    __swig_setmethods__["z"] = _hod.projwpk_params_z_set
    __swig_getmethods__["z"] = _hod.projwpk_params_z_get
    if _newclass:z = _swig_property(_hod.projwpk_params_z_get, _hod.projwpk_params_z_set)
    __swig_setmethods__["fkai"] = _hod.projwpk_params_fkai_set
    __swig_getmethods__["fkai"] = _hod.projwpk_params_fkai_get
    if _newclass:fkai = _swig_property(_hod.projwpk_params_fkai_get, _hod.projwpk_params_fkai_set)
    def __init__(self): 
        this = _hod.new_projwpk_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_projwpk_params
    __del__ = lambda self : None;
projwpk_params_swigregister = _hod.projwpk_params_swigregister
projwpk_params_swigregister(projwpk_params)


def dTime(*args):
  return _hod.dTime(*args)
dTime = _hod.dTime

def dChi(*args):
  return _hod.dChi(*args)
dChi = _hod.dChi

def dneffint(*args):
  return _hod.dneffint(*args)
dneffint = _hod.dneffint

def dCint(*args):
  return _hod.dCint(*args)
dCint = _hod.dCint

def findmvir(*args):
  return _hod.findmvir(*args)
findmvir = _hod.findmvir

def findksig(*args):
  return _hod.findksig(*args)
findksig = _hod.findksig

def dxi_L(*args):
  return _hod.dxi_L(*args)
dxi_L = _hod.dxi_L

def dPktest_L(*args):
  return _hod.dPktest_L(*args)
dPktest_L = _hod.dPktest_L

def dPktest_NL(*args):
  return _hod.dPktest_NL(*args)
dPktest_NL = _hod.dPktest_NL

def dPktest_zetaNL(*args):
  return _hod.dPktest_zetaNL(*args)
dPktest_zetaNL = _hod.dPktest_zetaNL

def dxi_NL(*args):
  return _hod.dxi_NL(*args)
dxi_NL = _hod.dxi_NL

def E_sq(*args):
  return _hod.E_sq(*args)
E_sq = _hod.E_sq

def dE_sqdz(*args):
  return _hod.dE_sqdz(*args)
dE_sqdz = _hod.dE_sqdz

def getall(*args):
  return _hod.getall(*args)
getall = _hod.getall

def d2lnE_sqdz2(*args):
  return _hod.d2lnE_sqdz2(*args)
d2lnE_sqdz2 = _hod.d2lnE_sqdz2

def gf_func(*args):
  return _hod.gf_func(*args)
gf_func = _hod.gf_func

def gf_jac(*args):
  return _hod.gf_jac(*args)
gf_jac = _hod.gf_jac

def findrz(*args):
  return _hod.findrz(*args)
findrz = _hod.findrz

def findzmax(*args):
  return _hod.findzmax(*args)
findzmax = _hod.findzmax

def dwpnl(*args):
  return _hod.dwpnl(*args)
dwpnl = _hod.dwpnl

def dwpl(*args):
  return _hod.dwpl(*args)
dwpl = _hod.dwpl

def dQk(*args):
  return _hod.dQk(*args)
dQk = _hod.dQk

def dxinlbar(*args):
  return _hod.dxinlbar(*args)
dxinlbar = _hod.dxinlbar

def dxinlbarbar(*args):
  return _hod.dxinlbarbar(*args)
dxinlbarbar = _hod.dxinlbarbar

def dxilbar(*args):
  return _hod.dxilbar(*args)
dxilbar = _hod.dxilbar

def dxilbarbar(*args):
  return _hod.dxilbarbar(*args)
dxilbarbar = _hod.dxilbarbar

def dwpnl_kaiser(*args):
  return _hod.dwpnl_kaiser(*args)
dwpnl_kaiser = _hod.dwpnl_kaiser

def dwpl_kaiser(*args):
  return _hod.dwpl_kaiser(*args)
dwpl_kaiser = _hod.dwpl_kaiser
class cosmology(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cosmology, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cosmology, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _hod.delete_cosmology
    __del__ = lambda self : None;
    def __init__(self, *args): 
        this = _hod.new_cosmology(*args)
        try: self.this.append(this)
        except: self.this = this
    def cosmo_free(self): return _hod.cosmology_cosmo_free(self)
    def Chiofz_num(self, *args): return _hod.cosmology_Chiofz_num(self, *args)
    def Chiofz(self, *args): return _hod.cosmology_Chiofz(self, *args)
    def Dlofz(self, *args): return _hod.cosmology_Dlofz(self, *args)
    def Daofz(self, *args): return _hod.cosmology_Daofz(self, *args)
    def Daofzlh(self, *args): return _hod.cosmology_Daofzlh(self, *args)
    def growthfactor_num(self, *args): return _hod.cosmology_growthfactor_num(self, *args)
    def dlnDdln1pz(self, *args): return _hod.cosmology_dlnDdln1pz(self, *args)
    def set_optmf(self, *args): return _hod.cosmology_set_optmf(self, *args)
    def Delta2_L(self, *args): return _hod.cosmology_Delta2_L(self, *args)
    def Delta2_NL(self, *args): return _hod.cosmology_Delta2_NL(self, *args)
    def Pk_L(self, *args): return _hod.cosmology_Pk_L(self, *args)
    def Pk_NL(self, *args): return _hod.cosmology_Pk_NL(self, *args)
    def init_powerspectra_NL(self, *args): return _hod.cosmology_init_powerspectra_NL(self, *args)
    def init_powerspectra_L(self): return _hod.cosmology_init_powerspectra_L(self)
    def Delta2_L_num(self, *args): return _hod.cosmology_Delta2_L_num(self, *args)
    def Delta2_NL_num(self, *args): return _hod.cosmology_Delta2_NL_num(self, *args)
    def xi_L(self, *args): return _hod.cosmology_xi_L(self, *args)
    def xi_NL(self, *args): return _hod.cosmology_xi_NL(self, *args)
    def xi_L_old(self, *args): return _hod.cosmology_xi_L_old(self, *args)
    def xi_NL_old(self, *args): return _hod.cosmology_xi_NL_old(self, *args)
    def init_xi_L(self): return _hod.cosmology_init_xi_L(self)
    def xi_L_num(self, *args): return _hod.cosmology_xi_L_num(self, *args)
    def init_xi_NL(self, *args): return _hod.cosmology_init_xi_NL(self, *args)
    def xi_NL_num(self, *args): return _hod.cosmology_xi_NL_num(self, *args)
    def Pktest_L(self, *args): return _hod.cosmology_Pktest_L(self, *args)
    def Pktest_NL(self, *args): return _hod.cosmology_Pktest_NL(self, *args)
    def Pktest_zetaNL(self, *args): return _hod.cosmology_Pktest_zetaNL(self, *args)
    def nofm(self, *args): return _hod.cosmology_nofm(self, *args)
    def bias(self, *args): return _hod.cosmology_bias(self, *args)
    def varM_TH_num(self, *args): return _hod.cosmology_varM_TH_num(self, *args)
    def varM_TH_num_deriv(self, *args): return _hod.cosmology_varM_TH_num_deriv(self, *args)
    def Nplus(self, *args): return _hod.cosmology_Nplus(self, *args)
    def getM(self, *args): return _hod.cosmology_getM(self, *args)
    def modelNFWhalo(self, *args): return _hod.cosmology_modelNFWhalo(self, *args)
    def modelNFWhalo_com(self, *args): return _hod.cosmology_modelNFWhalo_com(self, *args)
    def conc(self, *args): return _hod.cosmology_conc(self, *args)
    def ukofm(self, *args): return _hod.cosmology_ukofm(self, *args)
    def uskofm(self, *args): return _hod.cosmology_uskofm(self, *args)
    def ukinterp(self, *args): return _hod.cosmology_ukinterp(self, *args)
    def ukinit(self): return _hod.cosmology_ukinit(self)
    def ukinit2(self): return _hod.cosmology_ukinit2(self)
    def Eofz(self, *args): return _hod.cosmology_Eofz(self, *args)
    def setnew_z(self, *args): return _hod.cosmology_setnew_z(self, *args)
    __swig_setmethods__["z_glob"] = _hod.cosmology_z_glob_set
    __swig_getmethods__["z_glob"] = _hod.cosmology_z_glob_get
    if _newclass:z_glob = _swig_property(_hod.cosmology_z_glob_get, _hod.cosmology_z_glob_set)
    __swig_setmethods__["gf_glob"] = _hod.cosmology_gf_glob_set
    __swig_getmethods__["gf_glob"] = _hod.cosmology_gf_glob_get
    if _newclass:gf_glob = _swig_property(_hod.cosmology_gf_glob_get, _hod.cosmology_gf_glob_set)
    def gets8(self): return _hod.cosmology_gets8(self)
    def getOmb(self): return _hod.cosmology_getOmb(self)
    def geth(self): return _hod.cosmology_geth(self)
    def getns(self): return _hod.cosmology_getns(self)
    def getzeta_rmax(self): return _hod.cosmology_getzeta_rmax(self)
    def getzetamax(self): return _hod.cosmology_getzetamax(self)
    def getxinlzetamax(self): return _hod.cosmology_getxinlzetamax(self)
    def get_cfac(self): return _hod.cosmology_get_cfac(self)
    def set_cfac(self, *args): return _hod.cosmology_set_cfac(self, *args)
    def getzmax(self, *args): return _hod.cosmology_getzmax(self, *args)
    def getLmin(self, *args): return _hod.cosmology_getLmin(self, *args)
    def Time(self, *args): return _hod.cosmology_Time(self, *args)
    def Lookback(self, *args): return _hod.cosmology_Lookback(self, *args)
    def wpnl(self, *args): return _hod.cosmology_wpnl(self, *args)
    def wpl(self, *args): return _hod.cosmology_wpl(self, *args)
    __swig_setmethods__["fgm_m0"] = _hod.cosmology_fgm_m0_set
    __swig_getmethods__["fgm_m0"] = _hod.cosmology_fgm_m0_get
    if _newclass:fgm_m0 = _swig_property(_hod.cosmology_fgm_m0_get, _hod.cosmology_fgm_m0_set)
    __swig_setmethods__["fgm_slp"] = _hod.cosmology_fgm_slp_set
    __swig_getmethods__["fgm_slp"] = _hod.cosmology_fgm_slp_get
    if _newclass:fgm_slp = _swig_property(_hod.cosmology_fgm_slp_get, _hod.cosmology_fgm_slp_set)
    def xiNL_bar_num(self, *args): return _hod.cosmology_xiNL_bar_num(self, *args)
    def init_xiNL_bar(self, *args): return _hod.cosmology_init_xiNL_bar(self, *args)
    def xiNL_bar(self, *args): return _hod.cosmology_xiNL_bar(self, *args)
    def xiNL_barbar_num(self, *args): return _hod.cosmology_xiNL_barbar_num(self, *args)
    def init_xiNL_barbar(self, *args): return _hod.cosmology_init_xiNL_barbar(self, *args)
    def xiNL_barbar(self, *args): return _hod.cosmology_xiNL_barbar(self, *args)
    def xiL_bar_num(self, *args): return _hod.cosmology_xiL_bar_num(self, *args)
    def init_xiL_bar(self, *args): return _hod.cosmology_init_xiL_bar(self, *args)
    def xiL_bar(self, *args): return _hod.cosmology_xiL_bar(self, *args)
    def xiL_barbar_num(self, *args): return _hod.cosmology_xiL_barbar_num(self, *args)
    def init_xiL_barbar(self, *args): return _hod.cosmology_init_xiL_barbar(self, *args)
    def xiL_barbar(self, *args): return _hod.cosmology_xiL_barbar(self, *args)
    def wpnl_kaiser(self, *args): return _hod.cosmology_wpnl_kaiser(self, *args)
    def xi_NL_kaiser(self, *args): return _hod.cosmology_xi_NL_kaiser(self, *args)
    def wpl_kaiser(self, *args): return _hod.cosmology_wpl_kaiser(self, *args)
    def xi_L_kaiser(self, *args): return _hod.cosmology_xi_L_kaiser(self, *args)
    def renew(self, *args): return _hod.cosmology_renew(self, *args)
    def rsound(self): return _hod.cosmology_rsound(self)
    def get_deltapi(self, *args): return _hod.cosmology_get_deltapi(self, *args)
    def get_sinsqang(self, *args): return _hod.cosmology_get_sinsqang(self, *args)
    def get_logrp(self, *args): return _hod.cosmology_get_logrp(self, *args)
cosmology_swigregister = _hod.cosmology_swigregister
cosmology_swigregister(cosmology)

class np_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, np_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, np_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.np_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.np_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.np_params_cptr_get, _hod.np_params_cptr_set)
    __swig_setmethods__["z"] = _hod.np_params_z_set
    __swig_getmethods__["z"] = _hod.np_params_z_get
    if _newclass:z = _swig_property(_hod.np_params_z_get, _hod.np_params_z_set)
    __swig_setmethods__["Np"] = _hod.np_params_Np_set
    __swig_getmethods__["Np"] = _hod.np_params_Np_get
    if _newclass:Np = _swig_property(_hod.np_params_Np_get, _hod.np_params_Np_set)
    def __init__(self): 
        this = _hod.new_np_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_np_params
    __del__ = lambda self : None;
np_params_swigregister = _hod.np_params_swigregister
np_params_swigregister(np_params)

class c_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, c_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, c_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.c_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.c_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.c_params_cptr_get, _hod.c_params_cptr_set)
    def __init__(self): 
        this = _hod.new_c_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_c_params
    __del__ = lambda self : None;
c_params_swigregister = _hod.c_params_swigregister
c_params_swigregister(c_params)

class coll_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, coll_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, coll_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.coll_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.coll_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.coll_params_cptr_get, _hod.coll_params_cptr_set)
    __swig_setmethods__["sig"] = _hod.coll_params_sig_set
    __swig_getmethods__["sig"] = _hod.coll_params_sig_get
    if _newclass:sig = _swig_property(_hod.coll_params_sig_get, _hod.coll_params_sig_set)
    def __init__(self): 
        this = _hod.new_coll_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_coll_params
    __del__ = lambda self : None;
coll_params_swigregister = _hod.coll_params_swigregister
coll_params_swigregister(coll_params)

class mvir_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mvir_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mvir_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.mvir_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.mvir_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.mvir_params_cptr_get, _hod.mvir_params_cptr_set)
    __swig_setmethods__["m200"] = _hod.mvir_params_m200_set
    __swig_getmethods__["m200"] = _hod.mvir_params_m200_get
    if _newclass:m200 = _swig_property(_hod.mvir_params_m200_get, _hod.mvir_params_m200_set)
    __swig_setmethods__["z"] = _hod.mvir_params_z_set
    __swig_getmethods__["z"] = _hod.mvir_params_z_get
    if _newclass:z = _swig_property(_hod.mvir_params_z_get, _hod.mvir_params_z_set)
    def __init__(self): 
        this = _hod.new_mvir_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_mvir_params
    __del__ = lambda self : None;
mvir_params_swigregister = _hod.mvir_params_swigregister
mvir_params_swigregister(mvir_params)

class c200_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, c200_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, c200_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.c200_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.c200_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.c200_params_cptr_get, _hod.c200_params_cptr_set)
    __swig_setmethods__["cvir"] = _hod.c200_params_cvir_set
    __swig_getmethods__["cvir"] = _hod.c200_params_cvir_get
    if _newclass:cvir = _swig_property(_hod.c200_params_cvir_get, _hod.c200_params_cvir_set)
    __swig_setmethods__["omegaz"] = _hod.c200_params_omegaz_set
    __swig_getmethods__["omegaz"] = _hod.c200_params_omegaz_get
    if _newclass:omegaz = _swig_property(_hod.c200_params_omegaz_get, _hod.c200_params_omegaz_set)
    __swig_setmethods__["dcz"] = _hod.c200_params_dcz_set
    __swig_getmethods__["dcz"] = _hod.c200_params_dcz_get
    if _newclass:dcz = _swig_property(_hod.c200_params_dcz_get, _hod.c200_params_dcz_set)
    def __init__(self): 
        this = _hod.new_c200_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_c200_params
    __del__ = lambda self : None;
c200_params_swigregister = _hod.c200_params_swigregister
c200_params_swigregister(c200_params)

class cvar_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cvar_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cvar_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.cvar_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.cvar_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.cvar_params_cptr_get, _hod.cvar_params_cptr_set)
    __swig_setmethods__["R"] = _hod.cvar_params_R_set
    __swig_getmethods__["R"] = _hod.cvar_params_R_get
    if _newclass:R = _swig_property(_hod.cvar_params_R_get, _hod.cvar_params_R_set)
    __swig_setmethods__["z"] = _hod.cvar_params_z_set
    __swig_getmethods__["z"] = _hod.cvar_params_z_get
    if _newclass:z = _swig_property(_hod.cvar_params_z_get, _hod.cvar_params_z_set)
    __swig_setmethods__["psinit"] = _hod.cvar_params_psinit_set
    __swig_getmethods__["psinit"] = _hod.cvar_params_psinit_get
    if _newclass:psinit = _swig_property(_hod.cvar_params_psinit_get, _hod.cvar_params_psinit_set)
    def __init__(self): 
        this = _hod.new_cvar_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_cvar_params
    __del__ = lambda self : None;
cvar_params_swigregister = _hod.cvar_params_swigregister
cvar_params_swigregister(cvar_params)

class pk_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, pk_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, pk_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.pk_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.pk_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.pk_params_cptr_get, _hod.pk_params_cptr_set)
    __swig_setmethods__["k"] = _hod.pk_params_k_set
    __swig_getmethods__["k"] = _hod.pk_params_k_get
    if _newclass:k = _swig_property(_hod.pk_params_k_get, _hod.pk_params_k_set)
    __swig_setmethods__["z"] = _hod.pk_params_z_set
    __swig_getmethods__["z"] = _hod.pk_params_z_get
    if _newclass:z = _swig_property(_hod.pk_params_z_get, _hod.pk_params_z_set)
    def __init__(self): 
        this = _hod.new_pk_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_pk_params
    __del__ = lambda self : None;
pk_params_swigregister = _hod.pk_params_swigregister
pk_params_swigregister(pk_params)

class xi_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, xi_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, xi_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.xi_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.xi_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.xi_params_cptr_get, _hod.xi_params_cptr_set)
    __swig_setmethods__["r"] = _hod.xi_params_r_set
    __swig_getmethods__["r"] = _hod.xi_params_r_get
    if _newclass:r = _swig_property(_hod.xi_params_r_get, _hod.xi_params_r_set)
    __swig_setmethods__["z"] = _hod.xi_params_z_set
    __swig_getmethods__["z"] = _hod.xi_params_z_get
    if _newclass:z = _swig_property(_hod.xi_params_z_get, _hod.xi_params_z_set)
    def __init__(self): 
        this = _hod.new_xi_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_xi_params
    __del__ = lambda self : None;
xi_params_swigregister = _hod.xi_params_swigregister
xi_params_swigregister(xi_params)

class ksig_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ksig_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ksig_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.ksig_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.ksig_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.ksig_params_cptr_get, _hod.ksig_params_cptr_set)
    __swig_setmethods__["z"] = _hod.ksig_params_z_set
    __swig_getmethods__["z"] = _hod.ksig_params_z_get
    if _newclass:z = _swig_property(_hod.ksig_params_z_get, _hod.ksig_params_z_set)
    def __init__(self): 
        this = _hod.new_ksig_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_ksig_params
    __del__ = lambda self : None;
ksig_params_swigregister = _hod.ksig_params_swigregister
ksig_params_swigregister(ksig_params)

class projwp_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, projwp_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, projwp_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.projwp_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.projwp_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.projwp_params_cptr_get, _hod.projwp_params_cptr_set)
    __swig_setmethods__["R"] = _hod.projwp_params_R_set
    __swig_getmethods__["R"] = _hod.projwp_params_R_get
    if _newclass:R = _swig_property(_hod.projwp_params_R_get, _hod.projwp_params_R_set)
    __swig_setmethods__["z"] = _hod.projwp_params_z_set
    __swig_getmethods__["z"] = _hod.projwp_params_z_get
    if _newclass:z = _swig_property(_hod.projwp_params_z_get, _hod.projwp_params_z_set)
    def __init__(self): 
        this = _hod.new_projwp_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_projwp_params
    __del__ = lambda self : None;
projwp_params_swigregister = _hod.projwp_params_swigregister
projwp_params_swigregister(projwp_params)

class rz_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rz_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rz_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.rz_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.rz_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.rz_params_cptr_get, _hod.rz_params_cptr_set)
    __swig_setmethods__["z"] = _hod.rz_params_z_set
    __swig_getmethods__["z"] = _hod.rz_params_z_get
    if _newclass:z = _swig_property(_hod.rz_params_z_get, _hod.rz_params_z_set)
    __swig_setmethods__["tgt"] = _hod.rz_params_tgt_set
    __swig_getmethods__["tgt"] = _hod.rz_params_tgt_get
    if _newclass:tgt = _swig_property(_hod.rz_params_tgt_get, _hod.rz_params_tgt_set)
    def __init__(self): 
        this = _hod.new_rz_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_rz_params
    __del__ = lambda self : None;
rz_params_swigregister = _hod.rz_params_swigregister
rz_params_swigregister(rz_params)

class z_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, z_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, z_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cptr"] = _hod.z_params_cptr_set
    __swig_getmethods__["cptr"] = _hod.z_params_cptr_get
    if _newclass:cptr = _swig_property(_hod.z_params_cptr_get, _hod.z_params_cptr_set)
    __swig_setmethods__["mag"] = _hod.z_params_mag_set
    __swig_getmethods__["mag"] = _hod.z_params_mag_get
    if _newclass:mag = _swig_property(_hod.z_params_mag_get, _hod.z_params_mag_set)
    def __init__(self): 
        this = _hod.new_z_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_z_params
    __del__ = lambda self : None;
z_params_swigregister = _hod.z_params_swigregister
z_params_swigregister(z_params)

TINK = _hod.TINK
OFFNEW = _hod.OFFNEW
class phi_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, phi_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, phi_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["hptr"] = _hod.phi_params_hptr_set
    __swig_getmethods__["hptr"] = _hod.phi_params_hptr_get
    if _newclass:hptr = _swig_property(_hod.phi_params_hptr_get, _hod.phi_params_hptr_set)
    __swig_setmethods__["z"] = _hod.phi_params_z_set
    __swig_getmethods__["z"] = _hod.phi_params_z_get
    if _newclass:z = _swig_property(_hod.phi_params_z_get, _hod.phi_params_z_set)
    def __init__(self): 
        this = _hod.new_phi_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_phi_params
    __del__ = lambda self : None;
phi_params_swigregister = _hod.phi_params_swigregister
phi_params_swigregister(phi_params)

class proj_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, proj_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, proj_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["hptr"] = _hod.proj_params_hptr_set
    __swig_getmethods__["hptr"] = _hod.proj_params_hptr_get
    if _newclass:hptr = _swig_property(_hod.proj_params_hptr_get, _hod.proj_params_hptr_set)
    __swig_setmethods__["R"] = _hod.proj_params_R_set
    __swig_getmethods__["R"] = _hod.proj_params_R_get
    if _newclass:R = _swig_property(_hod.proj_params_R_get, _hod.proj_params_R_set)
    __swig_setmethods__["z"] = _hod.proj_params_z_set
    __swig_getmethods__["z"] = _hod.proj_params_z_get
    if _newclass:z = _swig_property(_hod.proj_params_z_get, _hod.proj_params_z_set)
    def __init__(self): 
        this = _hod.new_proj_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_proj_params
    __del__ = lambda self : None;
proj_params_swigregister = _hod.proj_params_swigregister
proj_params_swigregister(proj_params)

class xi_gd_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, xi_gd_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, xi_gd_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["hptr"] = _hod.xi_gd_params_hptr_set
    __swig_getmethods__["hptr"] = _hod.xi_gd_params_hptr_get
    if _newclass:hptr = _swig_property(_hod.xi_gd_params_hptr_get, _hod.xi_gd_params_hptr_set)
    __swig_setmethods__["r"] = _hod.xi_gd_params_r_set
    __swig_getmethods__["r"] = _hod.xi_gd_params_r_get
    if _newclass:r = _swig_property(_hod.xi_gd_params_r_get, _hod.xi_gd_params_r_set)
    __swig_setmethods__["z"] = _hod.xi_gd_params_z_set
    __swig_getmethods__["z"] = _hod.xi_gd_params_z_get
    if _newclass:z = _swig_property(_hod.xi_gd_params_z_get, _hod.xi_gd_params_z_set)
    def __init__(self): 
        this = _hod.new_xi_gd_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_xi_gd_params
    __del__ = lambda self : None;
xi_gd_params_swigregister = _hod.xi_gd_params_swigregister
xi_gd_params_swigregister(xi_gd_params)

class xi_gg_params(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, xi_gg_params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, xi_gg_params, name)
    __repr__ = _swig_repr
    __swig_setmethods__["hptr"] = _hod.xi_gg_params_hptr_set
    __swig_getmethods__["hptr"] = _hod.xi_gg_params_hptr_get
    if _newclass:hptr = _swig_property(_hod.xi_gg_params_hptr_get, _hod.xi_gg_params_hptr_set)
    __swig_setmethods__["r"] = _hod.xi_gg_params_r_set
    __swig_getmethods__["r"] = _hod.xi_gg_params_r_get
    if _newclass:r = _swig_property(_hod.xi_gg_params_r_get, _hod.xi_gg_params_r_set)
    __swig_setmethods__["z"] = _hod.xi_gg_params_z_set
    __swig_getmethods__["z"] = _hod.xi_gg_params_z_get
    if _newclass:z = _swig_property(_hod.xi_gg_params_z_get, _hod.xi_gg_params_z_set)
    def __init__(self): 
        this = _hod.new_xi_gg_params()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_xi_gg_params
    __del__ = lambda self : None;
xi_gg_params_swigregister = _hod.xi_gg_params_swigregister
xi_gg_params_swigregister(xi_gg_params)

class hodpars(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hodpars, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hodpars, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Mmin"] = _hod.hodpars_Mmin_set
    __swig_getmethods__["Mmin"] = _hod.hodpars_Mmin_get
    if _newclass:Mmin = _swig_property(_hod.hodpars_Mmin_get, _hod.hodpars_Mmin_set)
    __swig_setmethods__["siglogM"] = _hod.hodpars_siglogM_set
    __swig_getmethods__["siglogM"] = _hod.hodpars_siglogM_get
    if _newclass:siglogM = _swig_property(_hod.hodpars_siglogM_get, _hod.hodpars_siglogM_set)
    __swig_setmethods__["Msat"] = _hod.hodpars_Msat_set
    __swig_getmethods__["Msat"] = _hod.hodpars_Msat_get
    if _newclass:Msat = _swig_property(_hod.hodpars_Msat_get, _hod.hodpars_Msat_set)
    __swig_setmethods__["alpsat"] = _hod.hodpars_alpsat_set
    __swig_getmethods__["alpsat"] = _hod.hodpars_alpsat_get
    if _newclass:alpsat = _swig_property(_hod.hodpars_alpsat_get, _hod.hodpars_alpsat_set)
    __swig_setmethods__["Mcut"] = _hod.hodpars_Mcut_set
    __swig_getmethods__["Mcut"] = _hod.hodpars_Mcut_get
    if _newclass:Mcut = _swig_property(_hod.hodpars_Mcut_get, _hod.hodpars_Mcut_set)
    __swig_setmethods__["fac"] = _hod.hodpars_fac_set
    __swig_getmethods__["fac"] = _hod.hodpars_fac_get
    if _newclass:fac = _swig_property(_hod.hodpars_fac_get, _hod.hodpars_fac_set)
    __swig_setmethods__["csbycdm"] = _hod.hodpars_csbycdm_set
    __swig_getmethods__["csbycdm"] = _hod.hodpars_csbycdm_get
    if _newclass:csbycdm = _swig_property(_hod.hodpars_csbycdm_get, _hod.hodpars_csbycdm_set)
    def __init__(self): 
        this = _hod.new_hodpars()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hod.delete_hodpars
    __del__ = lambda self : None;
hodpars_swigregister = _hod.hodpars_swigregister
hodpars_swigregister(hodpars)


def dxi_gg(*args):
  return _hod.dxi_gg(*args)
dxi_gg = _hod.dxi_gg

def dxi_gd(*args):
  return _hod.dxi_gd(*args)
dxi_gd = _hod.dxi_gd

def dwp(*args):
  return _hod.dwp(*args)
dwp = _hod.dwp

def dwp2(*args):
  return _hod.dwp2(*args)
dwp2 = _hod.dwp2

def dsigma(*args):
  return _hod.dsigma(*args)
dsigma = _hod.dsigma

def dwp_kaiser(*args):
  return _hod.dwp_kaiser(*args)
dwp_kaiser = _hod.dwp_kaiser

def dxiggbarbar(*args):
  return _hod.dxiggbarbar(*args)
dxiggbarbar = _hod.dxiggbarbar

def dxiggbar(*args):
  return _hod.dxiggbar(*args)
dxiggbar = _hod.dxiggbar
class hod(cosmology):
    __swig_setmethods__ = {}
    for _s in [cosmology]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, hod, name, value)
    __swig_getmethods__ = {}
    for _s in [cosmology]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, hod, name)
    __repr__ = _swig_repr
    __swig_setmethods__["whichopt"] = _hod.hod_whichopt_set
    __swig_getmethods__["whichopt"] = _hod.hod_whichopt_get
    if _newclass:whichopt = _swig_property(_hod.hod_whichopt_get, _hod.hod_whichopt_set)
    __swig_setmethods__["hodp"] = _hod.hod_hodp_set
    __swig_getmethods__["hodp"] = _hod.hod_hodp_get
    if _newclass:hodp = _swig_property(_hod.hod_hodp_get, _hod.hod_hodp_set)
    def __init__(self, *args): 
        this = _hod.new_hod(*args)
        try: self.this.append(this)
        except: self.this = this
    def ncen(self, *args): return _hod.hod_ncen(self, *args)
    def nsat(self, *args): return _hod.hod_nsat(self, *args)
    def ncenz(self, *args): return _hod.hod_ncenz(self, *args)
    def nsatz(self, *args): return _hod.hod_nsatz(self, *args)
    def avmass_tot(self, *args): return _hod.hod_avmass_tot(self, *args)
    def avmass_cen(self, *args): return _hod.hod_avmass_cen(self, *args)
    def galaxy_bias(self, *args): return _hod.hod_galaxy_bias(self, *args)
    __swig_getmethods__["Np_nsat"] = _hod.hod_Np_nsat_get
    if _newclass:Np_nsat = _swig_property(_hod.hod_Np_nsat_get)
    __swig_setmethods__["xp"] = _hod.hod_xp_set
    __swig_getmethods__["xp"] = _hod.hod_xp_get
    if _newclass:xp = _swig_property(_hod.hod_xp_get, _hod.hod_xp_set)
    __swig_setmethods__["wp"] = _hod.hod_wp_set
    __swig_getmethods__["wp"] = _hod.hod_wp_get
    if _newclass:wp = _swig_property(_hod.hod_wp_get, _hod.hod_wp_set)
    def gets8(self): return _hod.hod_gets8(self)
    def geth(self): return _hod.hod_geth(self)
    def getOmb(self): return _hod.hod_getOmb(self)
    def getOmk(self): return _hod.hod_getOmk(self)
    def set_cfactor(self, *args): return _hod.hod_set_cfactor(self, *args)
    def changepar(self, *args): return _hod.hod_changepar(self, *args)
    def getnewpar(self, *args): return _hod.hod_getnewpar(self, *args)
    def Pk_gg_gd(self, *args): return _hod.hod_Pk_gg_gd(self, *args)
    def Pk_gg_gd_he(self, *args): return _hod.hod_Pk_gg_gd_he(self, *args)
    def D2gg_num(self, *args): return _hod.hod_D2gg_num(self, *args)
    def D2gd_num(self, *args): return _hod.hod_D2gd_num(self, *args)
    def xi_gg_gd(self, *args): return _hod.hod_xi_gg_gd(self, *args)
    def xi_gg(self, *args): return _hod.hod_xi_gg(self, *args)
    def xi_gd(self, *args): return _hod.hod_xi_gd(self, *args)
    def xigg_num(self, *args): return _hod.hod_xigg_num(self, *args)
    def xigd_num(self, *args): return _hod.hod_xigd_num(self, *args)
    def Wp_ESD(self, *args): return _hod.hod_Wp_ESD(self, *args)
    def Wp(self, *args): return _hod.hod_Wp(self, *args)
    def Wp_Kaiser(self, *args): return _hod.hod_Wp_Kaiser(self, *args)
    def ESD(self, *args): return _hod.hod_ESD(self, *args)
    def Sigma(self, *args): return _hod.hod_Sigma(self, *args)
    def pspec_halomodel(self, *args): return _hod.hod_pspec_halomodel(self, *args)
    def scale_dep_bias_crossr(self, *args): return _hod.hod_scale_dep_bias_crossr(self, *args)
    def resetz(self, *args): return _hod.hod_resetz(self, *args)
    def hod_free(self): return _hod.hod_hod_free(self)
    def _print(self, *args): return _hod.hod__print(self, *args)
    def sethalo_exc(self, *args): return _hod.hod_sethalo_exc(self, *args)
    def set_cen_offset_params(self, *args): return _hod.hod_set_cen_offset_params(self, *args)
    def set_inc_params(self, *args): return _hod.hod_set_inc_params(self, *args)
    def hod_renew(self, *args): return _hod.hod_hod_renew(self, *args)
    __swig_destroy__ = _hod.delete_hod
    __del__ = lambda self : None;
hod_swigregister = _hod.hod_swigregister
hod_swigregister(hod)

# This file is compatible with both classic and new-style classes.


